version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "*.sh"
    mode: 777
    owner: ec2-user
    type:
      - file
  - object: /home
    pattern: "ec2-user"
    mode: 755
    owner: ec2-user
    type:
      - directory

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: beforeInstall/sh
      timeout: 20
      runas: ec2-user