# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "master" branch.


name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ap-northeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  APPLICATION_NAME: deploy-alarmy              # CodeDeploy 애플리케이션 이름
  DEPLOYMENT_GROUP: master                     # CodeDeploy 배포 그룹 이름
  WAR_FILE: alarmy-0.0.1-SNAPSHOT.war          # war 파일 이름

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy to EC2
      run: |
        aws deploy create-deployment \
          --application-name YourCodeDeployApp \
          --deployment-group-name YourDeploymentGroup \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
